from pathlib import Path

from architecture_explorer import (
    analyze_project,
    build_mermaid_diagram,
    build_module_details,
    build_project_snapshot,
    render_hld_markdown,
    render_lld_markdown,
)


ROOT = Path(__file__).resolve().parent


def render_self_analysis() -> str:
    summary = analyze_project(ROOT)
    snapshot = build_project_snapshot(summary)
    modules = summary.get("modules", [])
    lines = [
        "# Repo Architecture Explorer: Self-Analysis",
        "",
        "> Generated by `python self_analysis.py` from the repository root.",
        "",
        "## Verification Snapshot",
        "",
        f"- Project: `{summary.get('project_name')}`",
        f"- Modules: {len(modules)}",
        f"- Dependency observations: {len(summary.get('dependency_edges', []))}",
        f"- Entrypoints: {', '.join(item['name'] for item in summary.get('entrypoints', [])) or 'none'}",
        "- Automated verification: `python -m pytest -q`",
        "",
        "## Layers",
        "",
    ]
    for layer, names in snapshot["layers"].items():
        lines.append(f"- **{layer}**: {', '.join(f'`{name}`' for name in names) or 'none'}")

    lines.extend(["", "## High Level Design", "", render_hld_markdown(summary)])
    lines.extend(["", "## Low Level Design", "", render_lld_markdown(summary)])
    lines.extend(["", "## Internal Component Drilldown", ""])
    for module in modules:
        details = build_module_details(summary, module["name"])
        dependencies = ", ".join(f"`{name}`" for name in details["dependencies"]) or "none"
        reverse_dependencies = ", ".join(f"`{name}`" for name in details["reverse_dependencies"]) or "none"
        lines.extend([
            f"### `{details['name']}`",
            f"- Layer: `{details['layer']}`",
            f"- Functions: {', '.join(f'`{name}`' for name in details['functions']) or 'none'}",
            f"- Dependencies: {dependencies}",
            f"- Used by: {reverse_dependencies}",
            "",
        ])

    lines.extend(["## Mermaid Dependency Graph", "", "```mermaid", build_mermaid_diagram(summary), "```", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    print(render_self_analysis())
